#! /bin/sh

export JAVA_HOME=/var/vcap/packages/java7/jdk1.7.0_75
export PATH=$PATH:$JAVA_HOME/bin
export PRODUCT_HOME=/var/vcap/packages/apimanager/wso2am-1.8.0
 
startcmd='<PRODUCT_HOME>/bin/wso2server.sh start > /dev/null &'
restartcmd='<PRODUCT_HOME>/bin/wso2server.sh restart > /dev/null &'
stopcmd='<PRODUCT_HOME>/bin/wso2server.sh stop > /dev/null &'
 
case "$1" in
start)
   echo "Configuration"
   cp /var/vcap/jobs/apimanager/conf/api-manager.xml $PRODUCT_HOME/repository/conf
   cp /var/vcap/jobs/apimanager/conf/master-datasources.xml $PRODUCT_HOME/repository/conf/datasources
   cp /var/vcap/packages/mysql_connector_java/mysql-connector-java-5.1.35/mysql-connector-java-5.1.35-bin.jar $PRODUCT_HOME/repository/components/lib

   echo "Starting the WSO2 API Manager Server ..."
   $PRODUCT_HOME/bin/wso2server.sh start > /dev/null &
;;
stop)
   echo "Stopping the WSO2 API Manager Server ..."
   $PRODUCT_HOME/bin/wso2server.sh stop > /dev/null &
;;
*)
   echo "Usage: $0 {start|stop}"
exit 1
esac
