#! /bin/sh

export JAVA_HOME=/var/vcap/packages/java7/jdk1.7.0_75
export PATH=$PATH:$JAVA_HOME/bin
export PRODUCT_HOME=/var/vcap/packages/bam/wso2bam-2.5.0
 
case "$1" in
start)
  echo "Configuration"

  if [ -f /var/vcap/packages/bam/wso2bam-2.5.0/repository/deployment/server/bam-toolbox ]
  then
    echo "found tbox file"
  else
    cp /var/vcap/jobs/bam/conf/bam-datasources.xml /var/vcap/packages/bam/wso2bam-2.5.0/repository/conf/datasources

    cp /var/vcap/packages/bam/API_Manager_Analytics.tbox /var/vcap/packages/bam/wso2bam-2.5.0/repository/deployment/server/bam-toolbox

    cp /var/vcap/packages/mysql_connector_java/mysql-connector-java-5.1.35/mysql-connector-java-5.1.35-bin.jar /var/vcap/packages/bam/wso2bam-2.5.0/repository/components/lib
  fi

  echo "Starting the WSO2 BAM Server ..."
  /var/vcap/packages/bam/wso2bam-2.5.0/bin/wso2server.sh start > /dev/null &
;;
stop)
  echo "Stopping the WSO2 BAM Server ..."
  /var/vcap/packages/bam/wso2bam-2.5.0/bin/wso2server.sh stop > /dev/null &
;;
*)
  echo "Usage: $0 {start|stop}"
exit 1
esac
